version: "3"
services:
  zen-node:
    build:
      context: ./zen-node
      dockerfile: Dockerfile
    command: zen-node --api *:5050 --addressdb --data-path "/home/ubuntu/zen-data"
    ports: 
      - 5050:5050
