version: "3"
services:
  web: 
    build: .
    command: npm run server:dev
    volumes:
      - .:/home/app/explorer
      - /home/app/explorer/node_modules
    ports: 
      - 3000:3000
      - 9229:9229
    depends_on:
      - db
      - redis
  db:
    image: postgres:12.4-alpine
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${db__password}
  redis:
    image: redis:5-alpine
    volumes:
      - './data/redis:/data'
    ports:
      - 6379:6379
