@startuml "database structure new"
!include ./helpers.puml

scale 1.3
title Explorer - more separation

Table(Address, "Address") {
  primary_key(id)
  address field_comment(as appears in wallet)
  addressBC field_comment(as appears in chain)
}

Table(Block, "Block") {
  primary_key(id)
  version
  hash
  parent
  blockNumber
  commitments
  timestamp
  difficulty
  nonce1
  nonce2
  transactionCount
}

Table(Transaction, "Transaction") {
  primary_key(id)
  foreign_key(BlockId)
  index field_comment(tx index in block)
  version
  hash
  inputCount
  outputCount
}

Table(TransactionAsset, "TransactionAsset") {
  primary_key(id)
  foreign_key(BlockId)
  foreign_key(TransactionId)
  asset
  totalInputAmount
  totalOutputAmount
}

Table(Input, "Input") {
  primary_key(id)
  foreign_key(TransactionId)
  foreign_key(TransactionAssetId)
  foreign_key(OutputId)
  index field_comment(input index in tx)
  outpointTXHash
  outpointIndex
  amount field_comment(output amount cached)
}

Table(Output, "Output") {
  primary_key(id)
  foreign_key(TransactionId)
  foreign_key(TransactionAssetId)
  lockType
  contractLockVersion
  address field_comment(as appears in wallet)
  addressBC field_comment(as appears in chain)
  asset
  amount
  index field_comment(output index in tx)
}

Table(AddressTransactions, "AddressTransactions") {
  foreign_key(AddressId)
  foreign_key(TransactionId)
}

Table(AddressTransactionAssets, "AddressTransactionAssets") {
  foreign_key(AddressId)
  foreign_key(TransactionAssetId)
  total field_comment(address total for this asset)
}

' relations
Block "1" <--> "*" Transaction
Block "1" <--> "*" TransactionAsset
Address "1" <--> "*" AddressTransactions
Address "1" <--> "*" AddressTransactionAssets
Transaction "1" <--> "*" AddressTransactions
Transaction "1" <--> "*" TransactionAsset
TransactionAsset "1" <--> "*" AddressTransactionAssets
Transaction "1" <--> "*" Output
Transaction "1" <--> "*" Input
TransactionAsset "1" <--> "*" Output
TransactionAsset "1" <--> "*" Input
Input "1" <--> "1" Output
@enduml